### ISSUE TITLE
bug: duplicate domain request when tunnel through other node

### ISSUE THREAD

**Issue by marverlous811** [8xFF/atm0s-reverse-proxy#47]
I set up two relayer nodes on my computer. Node 1 is the seed node. Then, I created an agent to connect to node 1. When I sent an HTTP request from node 1 to the agent's domain, it ran normally. But when I sent an HTTP request from node 2, it had an error message `Connection lost` . 

It's a log I when traced 

<img width="1506" alt="Screenshot 2024-09-09 at 13 42 45" src="https://github.com/user-attachments/assets/af888532-ff27-4249-bd1a-8e12b2c830e6">

**Comment by giangndm** [comment]
@marverlous811 I can reproduce above issue in my env, I will check it and send a PR soon

**Comment by giangndm** [comment]
@marverlous811 I fixed tunnel error with PR https://github.com/8xFF/atm0s-reverse-proxy/pull/48, can you try with it?

**Comment by marverlous811** [comment]
@giangndm I ran again with that PR, and it's okay. You can close this issue
